### ISSUE TITLE
schedule of services replace old link on bottom with new link

### ISSUE THREAD

**Issue by ruhondo** [stvladnj/stvladnj.github.io#9]
when fr serge provides schedule of services for jan-feb 2018, the old link to the old website located on bottom of the pdf file needs to be replaced with new link attached is the current schedule on the web site
  #
[stvladscheddec2017.pdf](https://github.com/stvladnj/stvladnj.github.io/files/1603545/stvladscheddec2017.pdf)

**Comment by pgmmpk** [comment]
Old link will work and automatically re-direct. Closing this request as this is addressed at Fr Serge, not this website.
